// docgen/mcp-tools emits docs/reference/mcp-tools.md from the
// canonical tool registry at internal/mcp.Tools. Source of truth is
// the Go code; this script is the bridge that surfaces it as a
// human-readable reference.
//
// Invoked by `make docs-regen` (writes the file) and `make docs-check`
// (writes to a tempfile, diffs against the checked-in copy, fails CI
// if they drift). The convention is: change the tool registry,
// regenerate, commit both in the same patch.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/osauer/ibkr/internal/mcp"
)

const defaultOutput = "docs/reference/mcp-tools.md"

// schema is the shape of mcp.Tool.JSONSchema we care about. The
// full JSON Schema spec has more, but tools currently use just the
// object/properties/required subset (see schemaObject in mcp/tools.go).
type schema struct {
	Properties map[string]json.RawMessage `json:"properties"`
	Required   []string                   `json:"required"`
}

// property is the per-parameter shape inside schema.Properties.
type property struct {
	Type        string `json:"type"`
	Description string `json:"description"`
}

func main() {
	output := flag.String("o", defaultOutput, "output path (- for stdout)")
	flag.Parse()

	body := render(mcp.Tools)

	if *output == "-" {
		os.Stdout.WriteString(body)
		return
	}
	if err := os.WriteFile(*output, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
}

// render produces the full markdown body for the tool registry.
func render(tools []mcp.Tool) string {
	out := &strings.Builder{}
	out.WriteString("# MCP tools reference\n\n")
	out.WriteString("*Generated by `scripts/docgen/mcp-tools`. Do not edit by hand — run `make docs-regen` after changing `internal/mcp/tools.go`.*\n\n")
	out.WriteString("These are the tools `ibkr mcp` exposes to MCP clients (Claude Code, claude-desktop, any other MCP host). Each entry lists the tool name an LLM picks against, the description the LLM reads to decide whether to invoke, and the parameter schema the LLM binds against.\n\n")
	out.WriteString(fmt.Sprintf("**%d tools** total. Listed in registration order, aligned with the agent-appropriate CLI commands. Local lifecycle commands such as `setup`, `update`, `restart`, `mcp`, `daemon`, and `version` are intentionally excluded from MCP tools.\n\n", len(tools)))

	for _, t := range tools {
		fmt.Fprintf(out, "## `%s`\n\n", t.Name)
		out.WriteString(strings.TrimSpace(t.Description))
		out.WriteString("\n\n")

		var sch schema
		if err := json.Unmarshal(t.JSONSchema, &sch); err == nil && len(sch.Properties) > 0 {
			renderProperties(out, sch)
		} else {
			out.WriteString("*No parameters.*\n\n")
		}
	}
	return out.String()
}

// renderProperties emits a table of parameters with name, type,
// required flag, and description. Sorted for deterministic output.
func renderProperties(out *strings.Builder, sch schema) {
	required := make(map[string]bool, len(sch.Required))
	for _, r := range sch.Required {
		required[r] = true
	}

	out.WriteString("**Parameters:**\n\n")
	out.WriteString("| Name | Type | Required | Description |\n")
	out.WriteString("|------|------|----------|-------------|\n")

	names := make([]string, 0, len(sch.Properties))
	for n := range sch.Properties {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		var prop property
		_ = json.Unmarshal(sch.Properties[name], &prop)
		req := "no"
		if required[name] {
			req = "**yes**"
		}
		typeStr := prop.Type
		if typeStr == "" {
			typeStr = "any"
		}
		desc := strings.ReplaceAll(prop.Description, "|", "\\|")
		desc = strings.ReplaceAll(desc, "\n", " ")
		fmt.Fprintf(out, "| `%s` | %s | %s | %s |\n", name, typeStr, req, desc)
	}
	out.WriteString("\n")
}
