

const state = {
  snapshot: null,
  governance: null,
  governanceRefreshInFlight: null,
  governanceRefreshTimer: null,
  governanceRefreshDueAt: 0,
  governanceRefreshTimerEnsureTrailing: false,
  governanceRefreshAfterFlight: false,
  governanceLastRefreshAt: 0,
  governanceRefreshSucceeded: null,
  reconciliationCheck: { busy: false, state: "", error: false },
  governanceCutoverReceipt: null,
  safeNotificationTest: { busy: false, state: "", error: false },
  governanceCutoverReview: { busy: false, state: "", error: false },
  alertSettings: { mode: "watch_and_act" },
  alertSettingsUpdate: { busy: false, state: "", error: false },
  alerts: [],
  attention: null,
  alertInboxV2: null,
  alertInboxV2FeedValid: null,
  alertInboxV2FeedError: "",
  attentionEpoch: 0,
  attentionReadInFlight: null,
  attentionRetryTimer: null,
  attentionStatus: { state: "", error: false },
  pushInspection: { state: "status unavailable", busy: false },
  vapidPublicKey: "",
  eventSource: null,
  reconnectTimer: null,
  connectionText: "Connecting",
  connectionOK: false,
  pairingRequired: false,
  authenticated: false,
  accountValueVisible: localStorage.getItem("ibkrAccountValueVisible") === "true",
  canaryDetailOpen: false,
  rulesDetailOpen: false,
  regimeDetailOpen: false,
  regimeCanaryExpansionInitialized: false,
  detailPreferenceSet: false,
  accountOverviewOpen: false,
  underlyingDetailOpen: false,
  portfolioDetailOpen: false,
  accountExposureOpen: false,
  protectionOpen: false,
  opportunitiesOpen: false,
  selectedMarket: localStorage.getItem("ibkrSelectedMarket") || "us",
  marketCalendarOverride: null,
  proposalMarketCalendars: {},
  proposalMarketCalendarBusy: {},
  selectedAlertID: null,
  clearedAlertFingerprint: localStorage.getItem("ibkrClearedAlertFingerprint") || "",
  ordersOpen: null,
  openOrderEdits: {},
  protectionPreviewBusy: "",
  protectionPreviews: {},
  protectionSubmitBusy: "",
  protectionSubmits: {},
  protectionSnapshotBusy: false,
  protectionSnapshotLastAt: 0,
  protectionSnapshotNotice: "",
  protectionQuoteTicks: {},
  protectionQtyOverrides: {},
  protectionDerisk: { percent: 25, busy: "", result: null, submitted: null, requestRef: "", previewedAt: 0, abort: null },
  opportunityPreviewBusy: "",
  opportunityPreviews: {},
  opportunitySubmitBusy: "",
  opportunitySubmits: {},
  opportunitySnapshotBusy: false,
  opportunitySnapshotLastAt: 0,
  opportunitySnapshotNotice: "",
  underlyingNotice: "",
  underlyingBusy: "",
  latestPurgeStatus: null,
  fallbackRefreshBusy: false,
  settings: null,
  activeTab: normalizedTab(localStorage.getItem("ibkrActiveTab") || "monitor"),
};

function normalizedTab(tab) {
  if (tab === "brief" || tab === "alerts" || tab === "orders" || tab === "settings") return tab;
  return "monitor";
}

export { normalizedTab, state };
