package spx

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/osauer/ibkr/v2/internal/daemon/corestore"
	"github.com/osauer/ibkr/v2/internal/xdgcache"
)

// MembersFilename is the canonical filename for the runtime-refreshed
// members cache. Lives alongside the rest of ibkr's per-feature cache
// subdirs under $XDG_CACHE_HOME/ibkr/spx-members/.
const MembersFilename = "sp500-members.json"

const (
	membersAuthorityScope      = "market/breadth/spx/members"
	membersStateKind           = "spx_members.current.v1"
	membersObservationKind     = "spx_members.snapshot.v1"
	membersObservationSource   = "wikipedia.sp500_constituents"
	membersAuthorityWriteTries = 4
)

var externalMembersAuthorities = struct {
	sync.RWMutex
	byPath map[string]*corestore.Store
}{byPath: map[string]*corestore.Store{}}

// MembersDefaultPath resolves the canonical legacy members-cache path. During
// normal daemon runtime the path is only the stable binding key for daemon.db;
// it is not read or written after UseCoreMembersStore succeeds.
func MembersDefaultPath() (string, error) {
	dir, err := xdgcache.CacheDir("spx-members")
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, MembersFilename), nil
}

// UseCoreMembersStore binds the exact runtime cache path to daemon.db. The
// existing document is fully validated before the binding is published. Once
// bound, LoadExternal, SaveExternal, and MembersFileExists never touch the
// legacy JSON path. A missing document is the intended clean-slate state and
// lets callers use the embedded release-time fallback.
func UseCoreMembersStore(path string, store *corestore.Store) error {
	if store == nil {
		return errors.New("SPX members: nil corestore")
	}
	key, err := canonicalMembersPath(path)
	if err != nil {
		return err
	}
	doc, ok, err := store.GetStateDocument(context.Background(), membersAuthorityScope, membersStateKind)
	if err != nil {
		return fmt.Errorf("read SPX members authority: %w", err)
	}
	if ok {
		if _, err := decodeMembersEnvelope(doc.JSON, true); err != nil {
			return fmt.Errorf("decode SPX members authority: %w", err)
		}
	}
	externalMembersAuthorities.Lock()
	externalMembersAuthorities.byPath[key] = store
	externalMembersAuthorities.Unlock()
	return nil
}

// MemberList returns the embedded S&P-500 membership baked into the
// binary at release time (members_data.go, regenerated by `make
// refresh-spx-members` on every release). asOf is the release-time
// timestamp.
//
// MemberList is the embedded-fallback accessor — it does not consult the
// attached daemon.db membership projection or the legacy import file.
// Callers that want runtime-current membership should:
//   - try LoadExternal first, fall back to MemberList on miss (this
//     is what the daemon's deferred members resolver does, see
//     server.go's resolveBreadthMembers), or
//   - read the live engine via engine.Members() (which the runtime
//     refresher updates via engine.SetMembers as reconstitutions land).
//
// The split keeps MemberList usable from cold contexts (CLI, startup, tests)
// without forcing them to know about daemon persistence.
//
// NOTE: new constituents from reconstitution are admitted to breadth
// with full weight from day 1 of inclusion. A "pending until 50d
// accrue" exclusion was scoped out as disproportionate complexity vs.
// the <1% noise on 1-3 names per quarter. Revisit if a user complains
// breadth reads materially off.
func MemberList() (members []string, asOf time.Time) {
	out := slices.Clone(sp500Members)
	return out, sp500AsOf
}

// LoadExternal reads the attached daemon.db projection, or the legacy file
// when no authority has been attached, and returns
// (members, asOf, true) when it passes every gate, or (nil, zero,
// false) otherwise. Gates (any failure → cached file is treated as
// absent):
//
//   - File missing or unreadable.
//   - Corrupt JSON.
//   - Version mismatch (future schema bump triggers cold rebuild).
//   - Sanity bounds: MinMembers ≤ count ≤ MaxMembers. A 600-name list
//     or a 200-name list means the parser tripped and we'd rather
//     keep computing against the embedded baseline than publish
//     nonsense.
//
// The function returns no error — every gate-fail collapses to "use
// embedded". The daemon's refresh path logs WHY a file was rejected
// before falling through; this helper is intentionally silent so it
// stays usable from non-daemon contexts (CLI, tests).
func LoadExternal(path string) (members []string, asOf time.Time, ok bool) {
	data, strict, ok := loadMembersPayload(path)
	if !ok {
		return nil, time.Time{}, false
	}
	env, err := decodeMembersEnvelope(data, strict)
	if err != nil {
		return nil, time.Time{}, false
	}
	out := slices.Clone(env.Members)
	return out, env.AsOf, true
}

// SaveExternal writes members + asOf atomically to daemon.db after attachment.
// Its file branch remains for the cutover codec and isolated legacy tests.
func SaveExternal(path string, members []string, asOf time.Time) error {
	if authority := membersAuthority(path); authority != nil {
		normalized, err := normalizeMembers(members)
		if err != nil {
			return err
		}
		env := membersFile{
			Version: currentMembersFileVersion, AsOf: asOf,
			Source: "wikipedia", URL: WikipediaURL,
			Count: len(normalized), Members: normalized,
		}
		if _, err := validateMembersEnvelope(env, true); err != nil {
			return err
		}
		payload, err := json.Marshal(env)
		if err != nil {
			return fmt.Errorf("marshal members authority: %w", err)
		}
		metadata, err := json.Marshal(struct {
			Version int    `json:"version"`
			Count   int    `json:"count"`
			Source  string `json:"source"`
			URL     string `json:"url"`
		}{currentMembersFileVersion, len(normalized), "Wikipedia", WikipediaURL})
		if err != nil {
			return fmt.Errorf("marshal members metadata: %w", err)
		}
		return saveMembersAuthority(context.Background(), authority, payload, metadata, asOf)
	}
	env := membersFile{
		Version: currentMembersFileVersion,
		AsOf:    asOf,
		Source:  "wikipedia",
		URL:     WikipediaURL,
		Count:   len(members),
		Members: members,
	}
	data, err := json.MarshalIndent(env, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal members file: %w", err)
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer func() {
		if tmp != nil {
			_ = tmp.Close()
		}
		_ = os.Remove(tmpPath)
	}()
	if _, err := tmp.Write(data); err != nil {
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp: %w", err)
	}
	tmp = nil
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename %s: %w", path, err)
	}
	return nil
}

// MembersFileExists reports whether path exists. Used by status
// rendering to decide between the "cache:DATE" and "embedded:DATE"
// source token without re-loading the file.
func MembersFileExists(path string) bool {
	if authority := membersAuthority(path); authority != nil {
		_, ok, err := authority.GetStateDocument(context.Background(), membersAuthorityScope, membersStateKind)
		return err == nil && ok
	}
	_, err := os.Stat(path)
	return err == nil || !errors.Is(err, fs.ErrNotExist)
}

func loadMembersPayload(path string) (payload []byte, strict, ok bool) {
	if authority := membersAuthority(path); authority != nil {
		doc, found, err := authority.GetStateDocument(context.Background(), membersAuthorityScope, membersStateKind)
		if err != nil || !found {
			return nil, true, false
		}
		return append([]byte(nil), doc.JSON...), true, true
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, false, false
	}
	return data, false, true
}

func membersAuthority(path string) *corestore.Store {
	key, err := canonicalMembersPath(path)
	if err != nil {
		return nil
	}
	externalMembersAuthorities.RLock()
	store := externalMembersAuthorities.byPath[key]
	externalMembersAuthorities.RUnlock()
	return store
}

func canonicalMembersPath(path string) (string, error) {
	if strings.TrimSpace(path) == "" {
		return "", errors.New("SPX members cache path is empty")
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve SPX members cache path: %w", err)
	}
	return filepath.Clean(abs), nil
}

func decodeMembersEnvelope(payload []byte, strict bool) (membersFile, error) {
	var env membersFile
	if err := json.Unmarshal(payload, &env); err != nil {
		return membersFile{}, err
	}
	return validateMembersEnvelope(env, strict)
}

func validateMembersEnvelope(env membersFile, strict bool) (membersFile, error) {
	if env.Version != currentMembersFileVersion || env.AsOf.IsZero() {
		return membersFile{}, fmt.Errorf("invalid members envelope: version=%d as_of=%s", env.Version, env.AsOf)
	}
	if n := len(env.Members); n < MinMembers || n > MaxMembers {
		return membersFile{}, fmt.Errorf("invalid members count %d", n)
	}
	normalized, err := normalizeMembers(env.Members)
	if err != nil {
		return membersFile{}, err
	}
	if strict && (env.Count != len(normalized) || env.Source != "wikipedia" || env.URL != WikipediaURL || !slices.Equal(env.Members, normalized)) {
		return membersFile{}, errors.New("members authority envelope is not canonical")
	}
	env.Count = len(normalized)
	env.Members = normalized
	return env, nil
}

func normalizeMembers(members []string) ([]string, error) {
	out := make([]string, 0, len(members))
	seen := make(map[string]struct{}, len(members))
	for _, raw := range members {
		symbol := strings.ToUpper(strings.TrimSpace(raw))
		if symbol == "" || strings.ContainsAny(symbol, "\r\n\t") {
			return nil, fmt.Errorf("invalid SPX member %q", raw)
		}
		if _, exists := seen[symbol]; exists {
			return nil, fmt.Errorf("duplicate SPX member %q", symbol)
		}
		seen[symbol] = struct{}{}
		out = append(out, symbol)
	}
	sort.Strings(out)
	return out, nil
}

func saveMembersAuthority(ctx context.Context, authority *corestore.Store, payload, metadata []byte, observedAt time.Time) error {
	for range membersAuthorityWriteTries {
		doc, ok, err := authority.GetStateDocument(ctx, membersAuthorityScope, membersStateKind)
		if err != nil {
			return err
		}
		var revision int64
		if ok {
			revision = doc.Revision
		}
		_, _, err = authority.CompareAndSwapStateDocumentWithObservations(ctx, corestore.StateDocumentCAS{
			ScopeKey: membersAuthorityScope, Kind: membersStateKind,
			ExpectedRevision: revision, JSON: payload,
		}, []corestore.ObservationInput{{
			ScopeKey: membersAuthorityScope, Source: membersObservationSource,
			Kind: membersObservationKind, ObservedAt: observedAt,
			ContentType: "application/json", Payload: payload, MetadataJSON: metadata, DecisionEligible: true,
		}})
		if !errors.Is(err, corestore.ErrRevisionConflict) {
			return err
		}
	}
	return fmt.Errorf("save SPX members authority: %w", corestore.ErrRevisionConflict)
}

// ValidateLegacyMembersObservation validates a legacy members payload for
// observation-only cutover without publishing it as current state.
func ValidateLegacyMembersObservation(payload []byte) (time.Time, int, error) {
	env, err := decodeMembersEnvelope(payload, true)
	if err != nil {
		return time.Time{}, 0, err
	}
	return env.AsOf, len(env.Members), nil
}

// ImportLegacyMembersObservation preserves exact legacy bytes as
// non-authorizing evidence. The caller supplies metadata containing the
// decision_eligible=false cutover marker.
func ImportLegacyMembersObservation(ctx context.Context, authority *corestore.Store, payload, metadata []byte, observedAt time.Time) error {
	_, err := authority.AppendObservation(ctx, corestore.ObservationInput{
		ScopeKey: membersAuthorityScope, Source: membersObservationSource,
		Kind: membersObservationKind, ObservedAt: observedAt,
		ContentType: "application/json", Payload: payload, MetadataJSON: metadata, DecisionEligible: false,
	})
	return err
}

// membersFile is the on-disk envelope. Mirrors the gamma-zero store's
// shape (version + descriptive fields + payload) but kept distinct
// because there's no benefit to sharing the type (the consumers are
// disjoint and the gate semantics differ).
type membersFile struct {
	Version int       `json:"version"`
	AsOf    time.Time `json:"as_of"`
	Source  string    `json:"source"`
	URL     string    `json:"url"`
	Count   int       `json:"count"`
	Members []string  `json:"members"`
}

// currentMembersFileVersion is bumped on any incompatible shape
// change. v1 is the initial layout; a future v2 (e.g. adding
// per-symbol inclusion dates for the pending-50d implementation)
// would bump this and let LoadExternal cold-rebuild from the embedded
// list while the next refresh writes the new shape.
const currentMembersFileVersion = 1
